name: Docker

on: 
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v2.0.0

    - name: Download a build artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: programa

    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: mathews8415
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v3.0.0
      with:
        # Build's context is the set of files located in the specified PATH or URL
        context: .
        # Path to the Dockerfile
        file: ./Dockerfile
        # Push is a shorthand for --output=type=registry
        push: true
        # List of tags
        tags: mathews8415/go_ci:${{github.ref_name}}